#Configuración
server:
  port: 8091

spring:
  config:
    import: "optional:configserver:"
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        serviceId: config-service
        enabled: true
      routes:
        - id: checkout-service
          uri: lb://checkout-service #lb loadbalancer
                #http://localhost:8082
          predicates:
            - Path=/checkout
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/products/**
          filters:
          - AddRequestHeader=X-Request-from, gateway
          - AddResponseHeader=X-Response-Red, Blue
eureka:
  instance:
    hostname: localhost
