server:
  port: 8084

spring:
  config:
    import: "optional:configserver:"
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        serviceId: config-service
        enabled: true
      routes:
        - id: checkout-service
          uri: lb://checkout-service #lb loadbalancer
                #http://localhost:8082
          predicates:
            - Path=/checkout

eureka:
  instance:
    hostname: localhost
