spring:
  application:
    name: gateway-service
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-service
  gateway:
    routes:
      - id: checkout-service
        uri: lb://checkout-service
        predicates:
          - Path=/checkout
        filters:
          - AddRequestHeader=X-Request-from, gateway
          - AddResponseHeader=X-Response-Red, Blue
      - id: products-service
        uri: lb://products-service
        predicates:
          - Path=/products
server:
  port: 8090
